
Vagrant.configure("2") do |config|
    config.vm.define "ngtc-srv" do |node|    
    
      node.vm.box = "sbeliakou/centos"

      node.vm.provider "virtualbox" do |vbox|
        #vbox.gui = false
        vbox.memory = "2048"
        vbox.name = "ngtc-srv"
      end

      node.vm.hostname = "ngtc-srv"
      #node.vm.network "forwarded_port", guest: 8000, host: 8000
      node.vm.network "private_network", ip: "192.168.99.20"

      node.vm.provision "shell", path: "./provision/ngtc_provision.sh"
      node.vm.provision "shell", path: "./provision/zxagt_provision.sh" 
  
    end 



    config.vm.define "zbx-srv" do |node|

      node.vm.box = "sbeliakou/centos"

      node.vm.provider "virtualbox" do |vbox|
        #vbox.gui = false
        vbox.memory = "2048"
        vbox.name = "zbx-srv"
      end

      node.vm.hostname = "zbx-srv"
      node.vm.network "private_network", ip: "192.168.99.10"

      node.vm.provision "shell", path: "./provision/zxsrv_provision.sh"
      node.vm.provision "shell", path: "./provision/zxagt_provision.sh"

    end


end


   